version: '2'
services:
  web4:
    image: sebsanuwu/dockerroundrobin:latest
    container_name: APPLBRoundRobin
    ports:
      - "42000:6000"
    depends_on:
      - web1
      - web2
      - web3

  web1:
    image: sebsanuwu/dockerlog:latest
    container_name: LogService1
    ports:
      - "35001:6000"
    depends_on:
      - db

  web2:
    image: sebsanuwu/dockerlog:latest
    container_name: LogService2
    ports:
      - "35002:6000"
    depends_on:
      - db

  web3:
    image: sebsanuwu/dockerlog:latest
    container_name: LogService3
    ports:
      - "35003:6000"
    depends_on:
      - db

  db:
    image: mongo:3.6.1
    container_name: MongoDB
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    command: mongod

volumes:
  mongodb:
  mongodb_config:




